package com.example.monitoring.domain;

public enum AuditAction {
    USER_SIGNUP, USER_LOGIN, USER_LOGOUT, USER_ROLE_CHANGED, USER_STATUS_CHANGED,
    DATABASE_CREATED, DATABASE_UPDATED, DATABASE_DELETED, DATABASE_PING,
    POLICY_UPDATED, PUSH_REGISTERED, PUSH_DELETED, WEBHOOK_CREATED, WEBHOOK_UPDATED, WEBHOOK_DELETED,
    AI_REPORT_REQUESTED
}
